/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './logout.component';
import * as i2 from './auth.service';
import * as i3 from '@angular/router';
const styles_LogoutComponent:any[] = ([] as any[]);
export const RenderType_LogoutComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_LogoutComponent,data:{}});
export function View_LogoutComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵeld(1,
      0,(null as any),(null as any),4,'div',[['class','col-md-8 col-md-offset-2']],
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted(-1,(null as any),['\n            '])),(_l()(),i0.ɵeld(3,0,(null as any),
      (null as any),1,'button',[['class','btn btn-danger']],(null as any),[[(null as any),
          'click']],(_v,en,$event) => {
        var ad:boolean = true;
        var _co:i1.LogoutComponent = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.onLogout()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),['Logout'])),
      (_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵted(-1,(null as any),
          ['\n    ']))],(null as any),(null as any));
}
export function View_LogoutComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'app-logout',
      ([] as any[]),(null as any),(null as any),(null as any),View_LogoutComponent_0,
      RenderType_LogoutComponent)),i0.ɵdid(1,49152,(null as any),0,i1.LogoutComponent,
      [i2.AuthService,i3.Router],(null as any),(null as any))],(null as any),(null as any));
}
export const LogoutComponentNgFactory:i0.ComponentFactory<i1.LogoutComponent> = i0.ɵccf('app-logout',
    i1.LogoutComponent,View_LogoutComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2JvcmFtb3MvRGVza3RvcC9Nb3NoIFByb2dyYW1taW5nL21hdGVyaWFscy8wMSBHZXR0aW5nIFN0YXJ0ZWQvYXR0YWNoZWRfZmlsZXMvMDA2IFNldHRpbmcgdXAgdGhlIENvdXJzZSBQcm9qZWN0L3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL2F1dGgvbG9nb3V0LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9ib3JhbW9zL0Rlc2t0b3AvTW9zaCBQcm9ncmFtbWluZy9tYXRlcmlhbHMvMDEgR2V0dGluZyBTdGFydGVkL2F0dGFjaGVkX2ZpbGVzLzAwNiBTZXR0aW5nIHVwIHRoZSBDb3Vyc2UgUHJvamVjdC9zZWVkLXByb2plY3QvYXNzZXRzL2FwcC9hdXRoL2xvZ291dC5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9ib3JhbW9zL0Rlc2t0b3AvTW9zaCBQcm9ncmFtbWluZy9tYXRlcmlhbHMvMDEgR2V0dGluZyBTdGFydGVkL2F0dGFjaGVkX2ZpbGVzLzAwNiBTZXR0aW5nIHVwIHRoZSBDb3Vyc2UgUHJvamVjdC9zZWVkLXByb2plY3QvYXNzZXRzL2FwcC9hdXRoL2xvZ291dC5jb21wb25lbnQudHMuTG9nb3V0Q29tcG9uZW50Lmh0bWwiLCJuZzovLy9Vc2Vycy9ib3JhbW9zL0Rlc2t0b3AvTW9zaCBQcm9ncmFtbWluZy9tYXRlcmlhbHMvMDEgR2V0dGluZyBTdGFydGVkL2F0dGFjaGVkX2ZpbGVzLzAwNiBTZXR0aW5nIHVwIHRoZSBDb3Vyc2UgUHJvamVjdC9zZWVkLXByb2plY3QvYXNzZXRzL2FwcC9hdXRoL2xvZ291dC5jb21wb25lbnQudHMuTG9nb3V0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgICAgIDxkaXYgY2xhc3M9XCJjb2wtbWQtOCBjb2wtbWQtb2Zmc2V0LTJcIj5cbiAgICAgICAgICAgIDxidXR0b24gY2xhc3M9XCJidG4gYnRuLWRhbmdlclwiIChjbGljayk9XCJvbkxvZ291dCgpXCI+TG9nb3V0PC9idXR0b24+XG4gICAgICAgIDwvZGl2PlxuICAgICIsIjxhcHAtbG9nb3V0PjwvYXBwLWxvZ291dD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLGtEQUNRO01BQUE7TUFBQSx3RUFBc0M7YUFBQSx1Q0FDbEM7TUFBQTtVQUFBO1FBQUE7UUFBQTtRQUErQjtVQUFBO1VBQUE7UUFBQTtRQUEvQjtNQUFBLGdDQUFvRDtNQUFlLGtEQUNqRTtVQUFBOzs7b0JDSGQ7TUFBQTtnQ0FBQSxVQUFBO01BQUE7OzsifQ==
