/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './heder.component.ngfactory';
import * as i2 from './heder.component';
import * as i3 from '@angular/router';
import * as i4 from './errors/error.component.ngfactory';
import * as i5 from './errors/error.component';
import * as i6 from './errors/error.service';
import * as i7 from './app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),9,'div',[['class',
      'container']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵeld(2,0,(null as any),
          (null as any),1,'app-header',([] as any[]),(null as any),(null as any),(null as any),
          i1.View_HederComponent_0,i1.RenderType_HederComponent)),i0.ɵdid(3,49152,
          (null as any),0,i2.HederComponent,([] as any[]),(null as any),(null as any)),
      (_l()(),i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵeld(5,0,(null as any),
          (null as any),0,'hr',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),['\n    '])),
      (_l()(),i0.ɵeld(7,16777216,(null as any),(null as any),1,'router-outlet',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      i0.ɵdid(8,212992,(null as any),0,i3.RouterOutlet,[i3.ChildrenOutletContexts,
          i0.ViewContainerRef,i0.ComponentFactoryResolver,[8,(null as any)],i0.ChangeDetectorRef],
          (null as any),(null as any)),(_l()(),i0.ɵted(-1,(null as any),['\n'])),(_l()(),
          i0.ɵted(-1,(null as any),['\n'])),(_l()(),i0.ɵeld(11,0,(null as any),(null as any),
          1,'app-error',([] as any[]),(null as any),(null as any),(null as any),i4.View_ErrorComponent_0,
          i4.RenderType_ErrorComponent)),i0.ɵdid(12,114688,(null as any),0,i5.ErrorComponent,
          [i6.ErrorService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,8,0);
    _ck(_v,12,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'my-app',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i0.ɵdid(1,49152,(null as any),0,i7.AppComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const AppComponentNgFactory:i0.ComponentFactory<i7.AppComponent> = i0.ɵccf('my-app',
    i7.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2JvcmFtb3MvRGVza3RvcC9Nb3NoIFByb2dyYW1taW5nL21hdGVyaWFscy8wMSBHZXR0aW5nIFN0YXJ0ZWQvYXR0YWNoZWRfZmlsZXMvMDA2IFNldHRpbmcgdXAgdGhlIENvdXJzZSBQcm9qZWN0L3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL2FwcC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvYm9yYW1vcy9EZXNrdG9wL01vc2ggUHJvZ3JhbW1pbmcvbWF0ZXJpYWxzLzAxIEdldHRpbmcgU3RhcnRlZC9hdHRhY2hlZF9maWxlcy8wMDYgU2V0dGluZyB1cCB0aGUgQ291cnNlIFByb2plY3Qvc2VlZC1wcm9qZWN0L2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2JvcmFtb3MvRGVza3RvcC9Nb3NoIFByb2dyYW1taW5nL21hdGVyaWFscy8wMSBHZXR0aW5nIFN0YXJ0ZWQvYXR0YWNoZWRfZmlsZXMvMDA2IFNldHRpbmcgdXAgdGhlIENvdXJzZSBQcm9qZWN0L3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL2FwcC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2JvcmFtb3MvRGVza3RvcC9Nb3NoIFByb2dyYW1taW5nL21hdGVyaWFscy8wMSBHZXR0aW5nIFN0YXJ0ZWQvYXR0YWNoZWRfZmlsZXMvMDA2IFNldHRpbmcgdXAgdGhlIENvdXJzZSBQcm9qZWN0L3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxuICAgIDxhcHAtaGVhZGVyPjwvYXBwLWhlYWRlcj5cbiAgICA8aHI+XG4gICAgPHJvdXRlci1vdXRsZXQ+PC9yb3V0ZXItb3V0bGV0PlxuPC9kaXY+XG48YXBwLWVycm9yPjwvYXBwLWVycm9yPiIsIjxteS1hcHA+PC9teS1hcHA+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUF1Qiw4Q0FDbkI7VUFBQTsrREFBQSxVQUFBO1VBQUE7TUFBeUIsOENBQ3pCO1VBQUE7VUFBQSw4QkFBSTtNQUNKO1VBQUE7YUFBQTswREFBQTtVQUFBLDZCQUErQiwwQ0FDN0I7aUJBQUEsMkJBQ047VUFBQTtzQ0FBQSxVQUFBO1VBQUE7SUFGSTtJQUVKOzs7O29CQ0xBO01BQUE7YUFBQTtVQUFBOzs7In0=
